### ISSUE TITLE
issue with statuscolors

### ISSUE THREAD

**Issue by Afify** [torrinfail/dwmblocks#1]
Added spaces  at the right corner, for each  raw characters '\x00' . 

[https://dwm.suckless.org/patches/statuscolors/](https://dwm.suckless.org/patches/statuscolors/)

**Comment by torrinfail** [comment]
Hello I looked at the issue and it looks like its an issue with the patch when drawing the text, rather than with dwmblocks. This sucks because I want to use the patch without having this issue as well. I'll let you know if I find a way to fix the patch.

**Comment by Afify** [comment]
thanks i found another patch to fix it


+	/* correction for colours */
+	int correct = 0; 
+	char *xcape = malloc (sizeof (char) * 128);
+	memset(xcape,0,sizeof (char) * 128);
+	for ( ; *ts != '\0' ; ts++) {    
+		if (*ts <= LENGTH(colors)) {
+			sprintf(xcape,"%c",*ts);
+			correct += TEXTW(xcape) - lrpad;
+		}
+	}
+	free(xcape);
+	ts = stext;
+

**Comment by sourjyo0** [comment]
Where do you add that?
