### ISSUE TITLE
patch for dwmblocks clickable modules

### ISSUE THREAD

**Issue by kronikpillow** [torrinfail/dwmblocks#11]
so since by your previous comment i realize you don't even realize how dwmblocks is actually popular, I wanted to share to you a patch made for your dwmblocks & statuscmd patch modified to be used with dwmblocks to have fully clickable modules in dwmblocks

[dwmblocks + dmw statuscmd signal patch](https://gist.github.com/danbyl/54f7c1d57fc6507242a95b71c3d8fdea)

this allows full clickability and compatibility with i3blocks modules ;)

**Comment by torrinfail** [comment]
So because you need to patch dwm in order for that to work, I don't want to merge it into the project. But I did just add the patch to the readme so people can apply it if they want.
