### ISSUE TITLE
broken symbol appearing next to some emoji's

### ISSUE THREAD

**Issue by rhysday** [torrinfail/dwmblocks#20]
After I did a format reinstall I now have funny symbols next to some emoji. I'm using Luke Smiths build of dwmblocks.

Example: <a href="https://imgur.com/RSCOuwM.png">
  <img src="https://imgur.com/RSCOuwM.png" />
</a>

**Comment by leorolland** [comment]
Same here 
![DeepinScreenshot_select-area_20200607175906](https://user-images.githubusercontent.com/7632179/83970773-d7ca0f00-a8d7-11ea-977f-fa91dee37520.png)

**Comment by leorolland** [comment]
I've found that installing the [statuscmd](https://dwm.suckless.org/patches/statuscmd/) patch to dwm solves the problem :)

**Comment by torrinfail** [comment]
This seems like an issue with dwm rather than dwmblocks which simply feeds dwm the text to display through the root window title. Any issues with how it is being displayed would almost certainly be a problem with dwm itself.
