### ISSUE TITLE
How to change the color of individual blocks font?

### ISSUE THREAD

**Issue by rhysday** [torrinfail/dwmblocks#23]
Hi just wondering how I would go about this? Thanks

**Comment by johanthoren** [comment]
I'm wondering the same thing. I tried using escape sequences, but that didn't work:
`echo -e " 🌐 \e[32m${vpn_ip} "`
It just printed the escape sequence in the bar.

**Comment by johanthoren** [comment]
> Hi just wondering how I would go about this? Thanks

If you are still looking for a way to do this, I had success with using the 'statuscolors' patch of dam. When that was applied dwmblocks showed my colors just fine. My implementation, for reference:
https://gitlab.com/johan.thoren/dwm-jt
https://gitlab.com/johan.thoren/dwmblocks-jt
https://gitlab.com/johan.thoren/statusbar-scripts

**Comment by torrinfail** [comment]
Yeah you need to patch dwm itself because dwmblocks doesn't actually display anything.
