### ISSUE TITLE
dwmblocks Sometimes stop.

### ISSUE THREAD

**Issue by utkarsh181** [torrinfail/dwmblocks#26]
Hi, thanks for dwmblocks
I am using Luke's build of dwmblocks but added some on my own module but once in a while dwmblocks stops running which I have verified from htop. But the problem is there is no set pattern(ie time) on which this happens. To counter this problem I run 
```
kill -HUP $(pidof -s dwm)
```
This refreshes dwm and dwmblocks itself but not solves the main problem.

**Comment by toniz4** [comment]
@utkarsh181 did you resolve the problem? i'm having the same problem.

**Comment by utkarsh181** [comment]
Hi, more me it was because of dwmblock module for another script. If you are using luke smith setup you should change this line and refresh your setup.
```
	{ MODKEY|ShiftMask,		XK_n,		spawn,		SHCMD("st -e newsboat;") }, // ; pkill -RTMIN+6 dwmblocks

```
