### ISSUE TITLE
The code doesn't conform to the current C Standard.

### ISSUE THREAD

**Issue by GasparVardanyan** [torrinfail/dwmblocks#27]
In blocks.h, you use some icons that may be missing from the extended source character set and lead to undefined behaviour.
ISO/IEC 9899 C Standard (WG14 n2454), $5.2.1 http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2454.pdf

**Comment by torrinfail** [comment]
I just changed the default config to not include emojis which resolves this issue.
