### ISSUE TITLE
openBSD - does signalling work?

### ISSUE THREAD

**Issue by rjl6789** [torrinfail/dwmblocks#31]
Hi,

I'm using openBSD.  I see you've made some commits recently targeting OpenBSD. I'm wondering how I actually make this work?

I see`SIGUSR1` is being used as a base.  If I `kill -l` the `SIGUSR1` has a signal value of 30.  If I've got a block with an update signal of 10 - I assumed I'd send either `kill -40 pidofdwmblocks` or `pkill -40 dwmblocks` - both of these fail with similar to `pkill: signalling pid 52624: Invalid argument` ? (I've also tried multiple numbers north of 30 to no avail)

How do you send the signal to dwmblocks to "make the magic happen" !

Thanks

Rob

**Comment by rjl6789** [comment]
Hi,

Ok - wrong end of stick.  Reading the code again I realise the OpenBSD changes are so just SIGUSR1 and SIGUSR2 can be used - because OpenBSD doesn't have the capability of defining more "custom" signals like FreeBSD and Linux.  Sorry for the spam!

Rob

**Comment by torrinfail** [comment]
Hey no worries. Glad to see someone else using OpenBSD with this.

**Comment by flyknight** [comment]
Hi @rjl6789 
Sorry for disturbing you!
I've tried using `kill -30 $(pgrep dwmblocks)` and `pkill -30 dwmblocks` but it only kills dwmblock and doesn't update the status bar.  In my blocks.h, I've already tried changing the update signal to 0 or 30 but still no avail.
How did you manage to use SIGUSR1 and SIGUSR2 to give update signals on OpenBSD?
Thanks!

**Comment by rjl6789** [comment]
Of the top of my head (and reserving the right to be completely wrong!) does `kill -s SIGUSR1 $(pgrep dwmblocks)` do the job? How about `pkill -SIGUSR1 dwmblocks` ?

I’m afraid I can’t remember what value SIGUSR1/2 are enumerated to I believe if you look at signal.h you should find them defined (from https://man.openbsd.org/signal.3) - note in the above commands you should type `SIGUSR1` not substitute a value.

hope that helps a little.. or at least gets on the right path...

**Comment by flyknight** [comment]
Thanks! 
The signals for `SIGUSR1` and `SIGUSR2` are 30 and 31 respectively but you're right that it increases readability.
After tinkering with the blocks.h a bit, it works after setting the update signal to 1 for `SIGUSR1` and 2 for `SIGUSR2`.

**Comment by swindlesmccoop** [comment]
> Hi @rjl6789 Sorry for disturbing you! I've tried using `kill -30 $(pgrep dwmblocks)` and `pkill -30 dwmblocks` but it only kills dwmblock and doesn't update the status bar. In my blocks.h, I've already tried changing the update signal to 0 or 30 but still no avail. How did you manage to use SIGUSR1 and SIGUSR2 to give update signals on OpenBSD? Thanks!

@flyknight I am using FreeBSD and having the exact same issue. I have tried killing with SIGUSR1, SIGUSR2, and 30, but they all kill the entire program. Is it possible for this to work on FreeBSD? @rjl6789 If you would be able to help as well, that would be great.
