### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by lord-123** [torrinfail/dwmblocks#4]
When I run `sudo make clean install` I get this error:
```
rm -f *.o *.gch dwmblocks
cc `pkg-config --cflags x11` `pkg-config --libs x11` dwmblocks.c -o dwmblocks
/tmp/cct2d6ET.o: In function `setroot':
dwmblocks.c:(.text+0x3d9): undefined reference to `XOpenDisplay'
dwmblocks.c:(.text+0x44b): undefined reference to `XStoreName'
dwmblocks.c:(.text+0x45a): undefined reference to `XCloseDisplay'
collect2: error: ld returned 1 exit status
Makefile:4: recipe for target 'output' failed
make: *** [output] Error 1
```

I am running ubuntu 18.04 and have libx11-dev installed. Are there any other packages I need or is this broken?

**Comment by crian** [comment]
should work fine with libx11 installed.
seems to be a linker issue.

**Comment by lord-123** [comment]
Yes, I do.

**Comment by lord-123** [comment]
I installed [Luke Smith's build](https://github.com/LukeSmithxyz/dwmblocks) and that installed just fine so maybe it has something to do with the Makefile.

**Comment by crian** [comment]
So pkg-config is the issue. Revert this commit 3906995607d60e2721a03db78d4f3f4b63cd6afb
It should build well after that.

**Comment by lord-123** [comment]
Works fine after that.

**Comment by warremkaw** [comment]
I ran into the same problem. `gcc` won't be able to link to `Xlib` due to the placement of the `-l` option (in this case retrieved by `pkg-config`). Placing the `-l` option after `dwmblocks.c` will fix this.

**Comment by emilhem** [comment]
> Placing the `-l` option after `dwmblocks.c` will fix this.

Damn, that was easy! The pull request #17 fixes this.
