### ISSUE TITLE
Conditional icons

### ISSUE THREAD

**Issue by keeganjk** [torrinfail/dwmblocks#44]
This would probably be considered more of a feature request than an "issue": I think having some way to implement "conditional" icons would be useful—for example, a different battery icon based on levels or different volume indicated based on muted/unmuted. I tried implementing this in the scripts I used themselves and tried to opt for no icon (`""`), and that seems to work fine, but implementing it directly into this program could be nice.

**Comment by paniash** [comment]
I think keeping it within scripts is the ideal choice, otherwise it'll introduce unnecessary bloat. At this point it would be like reinventing the wheel.

**Comment by torrinfail** [comment]
Yeah this seems like something better kept in individual scripts. Having an empty output be ignored in terms of not making extra delimiters for them was intentional, even if kinda cryptic.
