### ISSUE TITLE
No delimiter (`\0`) gives weird boxes

### ISSUE THREAD

**Issue by paniash** [torrinfail/dwmblocks#47]
Hi!

As mentioned in `blocks.def.h`, I'm trying to remove delimiters by using `\0`, but I seem to get these weird boxes.

I'd appreciate any help.

![pic-selected-210513-1845-54](https://user-images.githubusercontent.com/59497618/118130937-8ac1b780-b41b-11eb-9fcb-32de87a6ea41.png)

**Comment by mehmetumit** [comment]
#58 this should fix the issue

**Comment by torrinfail** [comment]
Applied #59 and fixed this bug.
