### ISSUE TITLE
dwmblock stops with error zsh:unknown signal  dwmblocks

### ISSUE THREAD

**Issue by JBlocklove** [torrinfail/dwmblocks#5]
When I run dwmblocks it will run for a minute or two before stopping with an error from zsh: `zsh: unknown signal  dwmblocks`. It seems to add an extra space in the error message before `dwmblocks`, so I'm not sure if zsh is just parsing something wrong?

I've looked around but I can't seem to find much about this unknown signal error. Any help would be greatly appreciated!

**Comment by JBlocklove** [comment]
I've tried running it on `bash` as well and it dies with the output: `Real-time signal 12`

**Comment by kronikpillow** [comment]
it has nothing to do with bash or ssh, dwmblocks is written in C, not in bash or zsh

**Comment by JBlocklove** [comment]
I know it doesn't really have to do with `zsh` or `bash` themselves - once I got a different error with `bash` my concern about `zsh` not parsing something right was pretty well gone, but it definitely is some kind of issue with how the signals are configured and how the shell environment reads them. I was hoping that by giving the error messages related to the signals from both shells it could help diagnose what was wrong.

I've already tried LukeSmith's build and it gives me the same issue, regardless of using my own scripts in his `config.h` or his scripts from LARBS.

**Comment by markcaudill** [comment]
I get the same issue and I'm working through it now. I'm not sure where that signal is coming from, but I've figured out that if dwmblocks receives a signal that it doesn't know about, it dies. I'm looking to see if it's feasible to have all unhandled signals between SIGRTMIN and SIGRTMAX ignored. If so I'll work on a patch and pull request.

**Comment by markcaudill** [comment]
Ok here's a patch that seems to work so far. But I'm not confident enough in it to make a pull request quite yet. I have no idea if this is the correct approach.

Basically, I created a dummy signal handler that does nothing. Then, before setting up the rest of the signal handlers, I initialize all real time handlers to use the dummy handler. Then the actual user handlers are set, overriding the dummy handlers.

```diff
diff --git a/dwmblocks.c b/dwmblocks.c
index 88bdfb0..7d4616d 100644
--- a/dwmblocks.c
+++ b/dwmblocks.c
@@ -13,6 +13,7 @@ typedef struct {
        unsigned int interval;
        unsigned int signal;
 } Block;
+void dummysighandler(int num);
 void sighandler(int num);
 void replace(char *str, char old, char new);
 void getcmds(int time);
@@ -67,7 +68,7 @@ void getcmds(int time)
 {
        const Block* current;
        for(int i = 0; i < LENGTH(blocks); i++)
-       {       
+       {
                current = blocks + i;
                if ((current->interval != 0 && time % current->interval == 0) || time == -1)
                        getcmd(current,statusbar[i]);
@@ -88,8 +89,12 @@ void getsigcmds(int signal)
 
 void setupsignals()
 {
+    /* initialize all real time signals with dummy handler */
+    for(int i = SIGRTMIN; i <= SIGRTMAX; i++)
+        signal(i, dummysighandler);
+
        for(int i = 0; i < LENGTH(blocks); i++)
-       {         
+       {
                if (blocks[i].signal > 0)
                        signal(SIGRTMIN+blocks[i].signal, sighandler);
        }
@@ -146,6 +151,14 @@ void statusloop()
        }
 }
 
+#ifndef __OpenBSD__
+/* this signal handler should do nothing */
+void dummysighandler(int signum)
+{
+    return;
+}
+#endif
+
 #ifndef __OpenBSD__
 void sighandler(int signum)
 {
@@ -163,7 +176,7 @@ void termhandler(int signum)
 int main(int argc, char** argv)
 {
        for(int i = 0; i < argc; i++)
-       {       
+       {
                if (!strcmp("-d",argv[i]))
                        delim = argv[++i][0];
                else if(!strcmp("-p",argv[i]))

```

**Comment by JBlocklove** [comment]
Interesting, seems to make some amount of sense to me. Thanks! Might not be the "best" fix, but it should work for now at least, and I certainly haven't come up with anything better.

Is there some way to add logging into the dummy handler to try to track down where the signal is coming from?

**Comment by markcaudill** [comment]
If you run it with strace (e.g. `strace -e trace=%signal dwmblocks`) you'll see a bunch of output like this:

```
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=861, si_uid=1000, si_status=0
, si_utime=0, si_stime=0} ---                                                          
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0                                            rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0                                           
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=863, si_uid=1000, si_status=0
, si_utime=0, si_stime=0} ---                                                          
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0                                            
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0                                           
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=865, si_uid=1000, si_status=0
, si_utime=0, si_stime=0} ---                                                          
--- SIGRT_12 {si_signo=SIGRT_12, si_code=SI_USER, si_pid=870, si_uid=1000} ---         
+++ killed by SIGRT_12 +++                                                             
Real-time signal 10
```

I'm assuming you're not using Arch since apparently this doesn't affect it for some reason. I'm using an Ubuntu derivative (Pop!_OS) and so [sigaction(2)](https://manpages.ubuntu.com/manpages/eoan/en/man2/sigaction.2.html) (search for `siginfo_t`) describes the information available in the signal struct and what they mean. `si_pid` appears to be the PID of the sender, but I was never able to actually capture what process that was.

**Comment by JBlocklove** [comment]
Interestingly enough, I am using Arch, which I think makes this problem just a bit stranger.

Distro notwithstanding, thanks for the strace info! When I have some time to poke around with it I'll try myself to track down where my unexpected signal is coming from.

**Comment by GioF** [comment]
Also having the same problem on debian buster.

**Comment by markcaudill** [comment]
> Also having the same problem on debian buster.

FYI I've submitted a [pull request](https://github.com/torrinfail/dwmblocks/pull/8) that essentially handles any otherwise unhandled signals. I'm not sure if it will be accepted or if it is even in line with the direction @torrinfail would like this project to go. But it's simple enough that you can try it out even whether it gets merged or not.

**Comment by torrinfail** [comment]
I've merged the pull request. I haven't had this issue myself so I can't verify that this does fix the issue but I am going to close the issue assuming it did.
