### ISSUE TITLE
Not working with autostart

### ISSUE THREAD

**Issue by ghost** [torrinfail/dwmblocks#51]
I use Devuan Chimaera, DWM 6.2, and dwmblocks current version.
I have problem with dwmblocks, why mine cant launch automatically with .xinitrc and cool autostart dwm patch?

this is my xinitrc file

exec dwmblocks &
exec dwm

this is my dwm config.h

static const char *const autostart[] = {
	"feh", "--bg-fill", "/mnt/430356562D272084/gambarrandom/Evening_on_Karl_Johan_Street.jpg", NULL,
	"dwmblocks", NULL,
	"mpd", NULL,
	"pulseaudio", NULL,
	NULL
};

**Comment by Nyx-alpha** [comment]
You are starting two instances of dwmblocks. One from the xinitrc and one from dwm.
