### ISSUE TITLE
Script not showing what it should

### ISSUE THREAD

**Issue by xebcam** [torrinfail/dwmblocks#63]
I have this script that shows the SSID and signal bars of the wifi network that I'm connect to.
```
#!/bin/sh
SSID=$(nmcli device wifi list | grep "*" | awk '{print $3}')
BARS=$(nmcli device wifi list | grep "*" | awk '{print $9}')

echo $SSID $BARS
```
When I run it in my terminal (st) it shows this
![image](https://user-images.githubusercontent.com/55932127/157334503-a1054c60-e62d-4369-9432-946bf0c221a1.png)

But this is what is shown in dwm bar
![image](https://user-images.githubusercontent.com/55932127/157335148-7fd8116e-f240-45a3-8ba5-7a57913ed408.png)

This is my blocks.def.h
```
//Modify this file to change what commands output to your statusbar, and recompile using the make command.
static const Block blocks[] = {
	/*Icon*/	/*Command*/		/*Update Interval*/	/*Update Signal*/
	{" ", "dwm-wifi",					20,		0},
	{"", "dwm-simple-battery",					60,		0},
	{" ", "dwmdate",					0,		0},
	{" ", "dwmclock",					1,		0},
};

//sets delimeter between status commands. NULL character ('\0') means no delimeter.
static char delim[] = " ";
static unsigned int delimLen = 5;
```
I've seen it display the files in my home directory too which is weird

**Comment by mehmetumit** [comment]
```sh
#!/bin/sh
nmcli -f IN-USE,SSID,BARS device wifi list | grep '*' | awk '{print $2,$3}'
```
Try this script

**Comment by xebcam** [comment]
Yes, it works much better. Thanks!

**Comment by mehmetumit** [comment]
You're welcome!
