### ISSUE TITLE
The patch from statuscmd in sucless.org throws error

### ISSUE THREAD

**Issue by yogeshdcool** [torrinfail/dwmblocks#66]
As the patch given in the readme doesn't works I applied [this](https://dwm.suckless.org/patches/statuscmd/dwmblocks-statuscmd-20210402-96cbb45.diff) but it too throws this error
```
dwmblocks.c:57:12: warning: ‘returnStatus’ defined but not used [-Wunused-variable]
   57 | static int returnStatus = 0;
      |   
```
What should I do?

**Comment by torrinfail** [comment]
I'm not really wanting to support or maintain any patches or forks. As much as that's a huge part of suckless style programs, the support for patches generally comes from the patch author, not the original author. I do wish you luck in your endeavors though.
