### ISSUE TITLE
dwmblocks not handling more than 5 blocks

### ISSUE THREAD

**Issue by ronniedroid** [torrinfail/dwmblocks#9]
Hello there

So I have been using dwmblocks for a while on my desktop (running void) and have had no problem with it. last night I tried my build on my laptop (running manjaro) and it was working fine until I added a battery block, at first i assumed it had to do with my battery scripts, but that was not the case, as if I disable any of the six blocks I have, dwmblocks works fine, If i re-enable the disabled one, I get the following message
```
fish: “dwmblocks” terminated by signal SIGSEGV (Address boundary error)
```

My blocks.h file
```
//Modify this file to change what commands output to your statusbar, and recompile using the make command.
static const Block blocks[] = {
	/*Icon*/	/*Command*/		/*Update Interval*/	/*Update Signal*/
	{"",      "kbdlayout",	  0,		 9},

	{"",      "brightness",	  0,		 11},

	{"",      "volume",				0,		 10},

	{"",      "clock",				60,		  0},

  {"",      "battery",			10,		  0},

	{"",     "internet",			60,		  0},
};

//sets delimeter between status commands. NULL character ('\0') means no delimeter.
static char delim = ' ';
```

please let me know if you need further details. thanks in advance.

**Comment by kronikpillow** [comment]
I use 12 blocks, and they work fine, but I use lukesmith's dwmblocks build, which is even clickable :D

**Comment by luxintra** [comment]
I also use Lukes dwmblocks build but I'm getting freezes, as in it stops updating.

**Comment by kronikpillow** [comment]
are you running his latest version od dwmblocks & dwm? his latest dwm build has a autostart dwmblocks option that refreshes dwm once you refresh dwm

**Comment by kronikpillow** [comment]
also luke's build is heavily modified so opening an issue to torrinfail won't change anything mate

**Comment by ronniedroid** [comment]
I'm using torrinfail version as like tends to put many useless things in his builds :-D.  I tried in two computers, if I have more than 5 blocks, it crashes

**Comment by LordRusk** [comment]
its not the amount of modules, it crashes if there is too many charectors after a while with the error `segmentation fault (core dumped)  dwmblocks`. This happens on patched or unpatched versions, im using some of lukes scripts, some of my own. This would be epic to fix because im someone who runs ~20 modules at any given time. I thought i'd give an actual error message rather then just talking about it so maybe torrinfail has something to go off of to fix it.

**Comment by rhysday** [comment]
I have 18 modules but now the last module gets cut off/disappears at the end of the bar (right). Is there any way to stop this?
